Food item card
Lebanon-02-WBC-Capstones/satisfying-food-web pull request #23
Opened 2021-07-20 18:07 UTC by Adnan-961

Feat: Added Food item card
Style: added separate style files for the component.
Comment: couldnt let the whole card to be clicked since it wasnt letting me use `useHistory()` because of the version. , only the food image is clickable. also the fav button can be clicked, but has no functionality yet.

2021-07-25 10:11 UTC, osamaakb requested changes
Format and lint before staging

2021-07-25 10:11 UTC, osamaakb commented on src/App.css
> +}
remove these and use tailwind

2021-07-25 10:11 UTC, osamaakb commented on src/components/Food-item-card/FoodItem.jsx
> +function FoodItem(FoodItem) {
please replace the props name with something more reasonable not the components name
```suggestion
function FoodItem(props) {
```

2021-07-25 10:11 UTC, osamaakb commented on src/components/Food-item-card/style.css
> +  } */
please remove the comments

2021-07-25 10:11 UTC, osamaakb commented on src/components/Food-item-card/style.css
> +    height: 15px !important;
why using css and you have tailwind, whyyyyyy?

2021-07-25 10:11 UTC, osamaakb commented on src/components/category/Category.jsx
> +// };
remove the comments

2021-07-25 10:14 UTC, osamaakb commented
folder name should be all capitale no `-` included

2021-07-29 17:51 UTC, Adnan-961 commented
![test1](https://user-images.githubusercontent.com/81489386/127540614-5e15b615-4b1a-4fb1-8fc1-9607895d1feb.PNG)
![test2](https://user-images.githubusercontent.com/81489386/127540629-b90c2171-24ef-48d3-8084-2716f79087d6.PNG)
code used for testing :

 let obj = {
    img: "https://nomadparadise.com/wp-content/uploads/2020/08/lebanese-food-1-1024x683.jpg",
    title: "Tabbouleh",
    id: "3",
    time: "34",
    cal: "330",
  };
<Food {...obj} />

2021-08-01 11:40 UTC, osamaakb commented
Looks good, few comments on the design, 
add more padding-top for the title and heart, 
the card bg should be white

2021-08-01 11:40 UTC, osamaakb commented
the width should be like 50%

2021-08-02 09:08 UTC, osamaakb approved these changes
Good job @Adnan-961

2021-08-02 09:08 UTC, merged