Filter time
Lebanon-02-WBC-Capstones/satisfying-food-web pull request #40
Opened 2021-08-01 14:28 UTC by Adnan-961

![time](https://user-images.githubusercontent.com/81489386/127774529-b9570df8-07ed-4431-a9cc-b82faab1c073.PNG)
snip on iphone x 
@osamaakb please let me know if you need further changes

2021-08-02 09:15 UTC, osamaakb commented
can you please close other PRs if you want to open a new one! Also, you don't have to create a new PR just fix the old one

2021-08-02 09:21 UTC, osamaakb requested changes
good job, just a small change

2021-08-02 09:21 UTC, osamaakb commented on src/components/FilterTime/FilterTime.jsx
> +  const [divClass, setClass] = useState(notClicked);
you can do a better naming for this like 
```suggestion
  const [isClickedStyle, setIsClickedStyle] = useState(notClicked);
```

2021-08-02 17:01 UTC, Adnan-961 commented
@osamaakb done

2021-08-03 10:39 UTC, osamaakb approved these changes

2021-08-03 10:39 UTC, merged